version: "3"
  
services:
  societe:
    container_name: societe
    build: 
      context: .
      dockerfile: ./dockerfile
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./app:/societe
    command: "yarn start" 