version: "3"
  
services:
  october:
    container_name: societe
    build: 
      context: .
      dockerfile: ./dockerfile
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - ./app:/societe
    command: "yarn start" 